repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
        exclude: '\.log$'
      - id: trailing-whitespace
        stages: [pre-commit]
        exclude: '\.log$'
      - id: mixed-line-ending
        args: ["--fix=auto"]
        stages: [pre-commit]
        exclude: '\.log$'
      - id: check-yaml
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
